//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cr.ArgParse.Tests.Assertions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FailMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cr.ArgParse.Tests.Assertions.FailMessage", typeof(FailMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections &apos;{2}&apos; have different sizes.
        ///Expected: {0}
        ///But was:  {1}.
        /// </summary>
        internal static string CollectionSizesMismatch {
            get {
                return ResourceManager.GetString("CollectionSizesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items at position {2} in collections do not match.
        ///Expected: {0}
        ///But was:  {1}.
        /// </summary>
        internal static string ItemMismatch {
            get {
                return ResourceManager.GetString("ItemMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with key {0} is not present in second dictionary..
        /// </summary>
        internal static string ItemNotInBothDictionaries {
            get {
                return ResourceManager.GetString("ItemNotInBothDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items with key &apos;{2}&apos; in dictionaries do not match.
        ///Expected: {0}
        ///But was:  {1}.
        /// </summary>
        internal static string ItemWithKeyMismatch {
            get {
                return ResourceManager.GetString("ItemWithKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{3} {4}&apos; of type &apos;{2}&apos; doesn&apos;t match.
        ///Expected: {0}
        ///But was:  {1}.
        /// </summary>
        internal static string PropertyMismatch {
            get {
                return ResourceManager.GetString("PropertyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References are not equal..
        /// </summary>
        internal static string ReferenceMismatch {
            get {
                return ResourceManager.GetString("ReferenceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare property &apos;{0}.{1}&apos;..
        /// </summary>
        internal static string UncomparableProperty {
            get {
                return ResourceManager.GetString("UncomparableProperty", resourceCulture);
            }
        }
    }
}
